version: "3.9"
services:
  webapp:
    build: 
      context: .
    depends_on:
    - db
    - redis
    load_args:
    - "channel=gscho"
    config_toml: |
      [[lol]]
      true = "lol"
  redis:
    pkg: core/redis
  db:
    pkg: core/postgres